version: "3.7"

x-consul: &consul
  image: consul:latest
  volumes:
    - consul:/consul

volumes:
  consul:

services:
  client:
    <<: *consul
    command: 'agent -retry-join server-bootstrap -client 0.0.0.0 -bind ''{{ GetInterfaceIP "eth0" }}'''
    depends_on:
      - server-bootstrap
    deploy:
      replicas: 2

  server:
    <<: *consul
    ports:
      - "8500:8500"
    depends_on:
      - server-bootstrap
    command: 'agent -server -retry-join server-bootstrap -client 0.0.0.0 -bind ''{{ GetInterfaceIP "eth0" }}'' -ui'
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

  server-bootstrap:
    image: consul
    command: 'agent -server -bootstrap-expect 3 -client 0.0.0.0 -bind ''{{ GetInterfaceIP "eth0" }}'''
    deploy:
      placement:
        constraints: [node.role == manager]

  register:
    image: gliderlabs/registrator
    command: -internal consul://server:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    deploy:
      mode: global

  echo:
    image: hashicorp/http-echo
    command: -listen=:8080 -text="hello world"
    ports:
      - "8080:8080"
    deploy:
      replicas: 2

  ngix:
    image: nginx
    ports:
      - "8000:80"
    deploy:
      replicas: 2
